// Common scalar Delta / Spark SQL types supported by Fabric Lakehouse.
// https://learn.microsoft.com/en-us/fabric/data-warehouse/data-types#autogenerated-data-types-in-the-sql-analytics-endpoint
// Nested types and runtime-dependent extensions are outside this initial slice.
export const DATA_TYPES = ['STRING', 'BOOLEAN', 'TINYINT', 'SMALLINT', 'INT', 'BIGINT', 'FLOAT', 'DOUBLE', 'DECIMAL', 'DATE', 'TIMESTAMP', 'BINARY'] as const;
export interface ColumnReference { tableId: string; columnId: string; role?: 'value' | 'dependency' }
export interface RuleDependency { tableId: string; columnId: string; rule: 'joins' | 'filters' | 'deduplication' | 'aggregation' | 'loading' }
export interface Column {
  id: string;
  name: string;
  type: typeof DATA_TYPES[number];
  precision: number;
  scale: number;
  primaryKey?: boolean;
  foreignKey?: boolean;
  businessKey?: boolean;
  mapping?: {
    kind: 'source' | 'alias' | 'derived' | 'external';
    sources: ColumnReference[];
    expression: string;
    noInputs?: boolean;
    externalSource?: string;
  };
}
export interface TableNode {
  id: string; name: string; database: string; schema: string;
  logic: string;
  transformation?: Partial<Record<'joins' | 'filters' | 'deduplication' | 'aggregation' | 'loading', string>>;
  ruleDependencies?: RuleDependency[];
  columns: Column[]; upstream: string[]; x: number; y: number;
}
export const formatType = (column: Column) => column.type === 'DECIMAL' ? `DECIMAL(${column.precision},${column.scale})` : column.type;
